# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('nom_latin_genre', models.CharField(max_length=200)),
                ('nom_latin_espece', models.CharField(max_length=200)),
                ('faculte_germinative', models.IntegerField(null=True, verbose_name='Faculté germinative en années')),
                ('temps_levee', models.IntegerField(null=True, verbose_name='Temps de levée en jours')),
                ('description', models.TextField(blank=True, null=True)),
                ('gen_periode_recolte', models.BooleanField(default=False)),
                ('gen_periode_semis', models.BooleanField(default=False)),
                ('gen_forme', models.BooleanField(default=False)),
                ('gen_conservation', models.BooleanField(default=False)),
                ('gen_vitesse_croissance', models.BooleanField(default=False)),
                ('gen_utilisation_culinaire', models.BooleanField(default=False)),
                ('image_espece', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lutte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModalitePratique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_variante', models.IntegerField(null=True)),
                ('nom_modalite', models.CharField(max_length=200)),
                ('valeur_modalite', models.CharField(max_length=200)),
                ('image_pratique', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PbCulture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_pb_culture', models.ImageField(upload_to='')),
                ('id_espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Espece')),
                ('id_lutte', models.ManyToManyField(to='base_connaissances.Lutte')),
            ],
        ),
        migrations.CreateModel(
            name='PlantesAmies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_relation', models.CharField(max_length=200)),
                ('id_espece1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Espece')),
            ],
        ),
        migrations.CreateModel(
            name='PlantesAmies2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_espece2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Espece')),
            ],
        ),
        migrations.CreateModel(
            name='Pratique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Action')),
                ('id_espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Espece')),
            ],
        ),
        migrations.CreateModel(
            name='Ravageur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('remarque', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VarieteGenerique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('remarque', models.TextField(blank=True, null=True)),
                ('periode_recolte', models.CharField(max_length=200)),
                ('periode_semis', models.CharField(max_length=200)),
                ('forme', models.CharField(max_length=200)),
                ('conservation', models.CharField(max_length=200)),
                ('vitesse_croissance', models.CharField(max_length=200)),
                ('utilisation_culinaire', models.CharField(max_length=200)),
                ('id_espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Espece')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneGEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificateur_printemps', models.IntegerField(null=True)),
                ('modificateur_automne', models.IntegerField(null=True)),
                ('modificateur_croissance', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='variete',
            name='id_variete_generique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.VarieteGenerique'),
        ),
        migrations.AddField(
            model_name='plantesamies',
            name='id_espece2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.PlantesAmies2'),
        ),
        migrations.AddField(
            model_name='pbculture',
            name='id_ravageur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Ravageur'),
        ),
        migrations.AddField(
            model_name='modalitepratique',
            name='id_pratique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Pratique'),
        ),
        migrations.AddField(
            model_name='modalitepratique',
            name='id_variete_generique',
            field=models.ManyToManyField(to='base_connaissances.VarieteGenerique'),
        ),
        migrations.AddField(
            model_name='espece',
            name='id_famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_connaissances.Famille'),
        ),
        migrations.AlterUniqueTogether(
            name='varietegenerique',
            unique_together=set([('id_espece', 'nom')]),
        ),
    ]
