# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_connaissances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espece',
            name='image_espece',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
