# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_connaissances', '0002_auto_20180219_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varietegenerique',
            name='conservation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='varietegenerique',
            name='forme',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='varietegenerique',
            name='periode_recolte',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='varietegenerique',
            name='periode_semis',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='varietegenerique',
            name='utilisation_culinaire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='varietegenerique',
            name='vitesse_croissance',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
