# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_connaissances', '0003_auto_20180220_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitepratique',
            name='image_pratique',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pbculture',
            name='image_pb_culture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
